### ISSUE TITLE
Prevent abuse by requiring the card's billing country to match the geolocation

### ISSUE THREAD

**Issue by elearningplugins** [cferdinandi/gmt-pricing-parity#2]
I had a customer based in Turkey that was able to purchase my WordPress plugin with a 72% discount due to the pricing parity plugin.  That's expected.  However, her card's billing address was from Ohio in the United States.

From what I can gather, she's living abroad in Turkey.  So, she was able to take advantage of the pricing parity.  I would imagine if someone is VPN'ing into another country, they'd also be able to get the discount.

The only way to prevent this abuse (potentially) would be to have the billing address of the card match the Geolocation of the ip.

For reference, my site is using the Stripe payment gateway and I require the full billing address details.

**Comment by cferdinandi** [comment]
Hey, so, short answer: yes, someone absolutely can "cheat" by using a VPN to make a purchase from a country they don't live in, and I don't plan to do a damn thing about it.

I get into my thinking around this more in my article, [Running a trust-based business](https://gomakethings.com/running-a-trust-based-business/):

> Two years ago, I rolled out discounts on my products for students and for people who are part of under-represented groups in technology.
>
> When I did, I decided that rather than build in some sort of system that requires people to prove to me they’re a student or a member of an under-represented group, it was both easier for me and better for my customers if I operated from a place of trust...
>
> I believe that people are generally good, and will do the right thing...
> 
> This isn’t something that just a small, scrappy business-of-one can get away with, either. Apple runs a robust student discount program and doesn’t verify that you’re a student before checkout.

Beyond just not caring enough to do anything about it, it's technically difficult. 

Not every checkout setup requires an address or zip code to check against. Not all gateways share that information back to EDD at all (for example, PayPal Express manages all of that information and shares back a validated token instead of personal information).

And even if you *did* have access to every customer's address, you can't effectively evaluate if the purchase is legitimate or not based on that.

Maybe they're an expat living in another country. Why shouldn't they pay local prices based on where they live?

**Comment by elearningplugins** [comment]
You're absolutely right.  Thanks for that response.
